version: '3.8'

services:
  go-app:
    container_name: go-app
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}  
    ports:
      - "8080:8080"
    depends_on:
      - go_db
    restart: always

  go_db:
    container_name: go_db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  pgdata: